# write a python program to get two numbers from the user , and then make all arthimetic operations on the two numbers =>
frist_num = float(input("please enter the frist number is = "))
second_num = float(input("please enter the second number is = "))
print("the values of the two number is : \n")
print("the frist number is = "+str(frist_num))
print("the second number is = "+str(second_num))
print("all arthimetic operations on the two numbers is : \n")
print("the result of the addition arthimetic operation on the two numbers is = "+str(frist_num + second_num))
print("the result of the subtraction arthimetic operation on the two numbers is = "+str(frist_num - second_num))
print("the result of the multiplication arthimetic operation on the two numbers is = "+str(frist_num * second_num))
print("the result of the division arthimetic operation on the two numbers is = "+str(frist_num / second_num))
print("the result of the modulus arthimetic operation on the two numbers is = "+str(frist_num % second_num))