# write a python program to create file , and write user name , user age , user address , user faculty , user university , user gender , and at the end user birth date in the file => 
createFile = open("informationOfUser.txt" , "w+")
frist_user_name = input("please enter the frist name of the user is : ")
createFile.write("the frist name of the user is : \""+frist_user_name+"\"\n")
second_user_name = input("please enter the second name of the user is : ")
createFile.write("the second name of the user is : \""+second_user_name+"\"\n")
last_user_name = input("please enter the last name of the user is : ")
createFile.write("the last name of the user is : \""+last_user_name+"\"\n")
full_user_name = frist_user_name +"\t"+second_user_name+"\t"+ last_user_name 
createFile.write("the full name of the user is : \""+full_user_name+"\"\n")
user_age = int(input("please enter the age of the user is : "))
createFile.write("the age of the user is : \""+str(user_age)+" years\"\n")
user_address = input("please enter the address of the user is : ")
createFile.write("the address of the user is : \""+user_address+"\"\n")
user_faculty = input("please enter the faculty of the user is : ")
createFile.write("the faculry of the user is : \""+user_faculty+"\"\n")
user_university = input("please enter the university of the user is : ")
createFile.write("the university of the user is : \""+user_university+"\"\n")
user_gender = input("please enter the gender of the user is : ")
createFile . write("the gender of the user is : \""+user_gender+"\"\n")
user_birth_date = input("please enter the birth date of the user is : ")
createFile . write("the birth date of the user is : \""+user_birth_date+"\"\n")
createFile.close()