# write a python program to get four numbers from the user , and then get the result of the equation (e = d + a + 2ab / d * (4c + 10)) by using function methods =>
# frist_number = float(input("please enter the frist number is = "))
# second_number = float(input("please enter the second number is = "))
# third_number = float(input("please enter the third number is = "))
# fourth_number = float(input("please enter the fourth number is = "))
# def get_result_of_equation_of_numbers(fri_num , sec_num , thi_num , for_num) :
#     print("the different values of the different numbers is : \n")
#     print("the frist number is = "+str(fri_num))
#     print("the second number is = "+str(sec_num))
#     print("the third number is = "+str(thi_num))
#     print("the fourth number is = "+str(for_num))
#     result_of_equation_of_numbers = for_num + fri_num + 2 * fri_num * sec_num / for_num * (4 * thi_num + 10)
#     print("the result of the equation of the numbers is = "+str(result_of_equation_of_numbers))
# get_result_of_equation_of_numbers(frist_number , second_number , third_number , fourth_number)

def get_result_of_equation_of_numbers(fri_num , sec_num , thi_num , for_num) :
    print("the different values of the different numbers is : \n")
    print("the frist number is = "+str(fri_num))
    print("the second number is = "+str(sec_num))
    print("the third number is = "+str(thi_num))
    print("the fourth number is = "+str(for_num))
    result_of_equation_of_numbers = for_num + fri_num + 2 * fri_num * sec_num / for_num * (4 * thi_num + 10)
    return("the result of the equation of the numbers is = "+str(result_of_equation_of_numbers))
frist_number = float(input("please enter the frist number is = "))
second_number = float(input("please enter the second number is = "))
third_number = float(input("please enter the third number is = "))
fourth_number = float(input("please enter the fourth number is = "))
result_of_equation = get_result_of_equation_of_numbers(frist_number , second_number , third_number , fourth_number)
print(result_of_equation)