# write a python program to get all arthimetic operations on the three numbers =>
frist_num = float(input("please enter the frist number is = "))
second_num = float(input("please enter the second number is = "))
third_num = float(input("please enter the third number is = "))
print("the values of the three numbers is : \n")
print("the frist number is = "+str(frist_num))
print("the second number is = "+str(second_num))
print("the third number is = "+str(third_num))
print("all arthimetic operations on the three numbers is : \n")
print("the result of the addition arthimetic operation on the three numbers is = "+str(frist_num + second_num + third_num))
print("the result of the subtraction arthimetic operation on the three numbers is = "+str(frist_num - second_num - third_num))
print("the result of the multiplication arthimetic operaiton on the three numbers is = "+str(frist_num * second_num * third_num))
print("the result of the division arthimetic operation on the three numbers is = "+str(frist_num / second_num / third_num))
print("the result of the modulus arthimetic operation on the three numbers is = "+str(frist_num % second_num % third_num))