# write a python program to get different information from the user like name , father name , cnic , age , contact number , and then display all information , and then update cnic , age , contact number , and display student information again =>
student_name = input("please enter the name of the student is : ")
student_father_name = input("please enter the name of the student father is : ")
student_cnic = input("please enter the computerized national identify card of the student is : ")
student_age = float(input("please enter the age of the student is = "))
student_contact_number = input("please enter the phone number of the student is = ")
print("different information of the student before updating the student cnic , student age , and at the end student phone number is : \n")
print("the name of the student is : \""+str(student_name)+"\"")
print("the name of the father of the student is : \""+student_father_name+"\"")
print("the computerized national identify card of the student is : \""+student_cnic+"\"")
print("the age of the student is : \""+str(student_age)+"\"")
print("the phone number of the student is : \""+student_contact_number+"\"")
student_cnic = input("please enter the new value of the computerized national identify card is : ")
student_age = float(input("please enter the new value of the student age is = "))
student_contact_number = input("please enter the new value of the contact number of the student is : ")
print("different information of the student after updation student cnic , student age , and at the end student phone number is : \n")
print("the name of the student is : \""+student_name+"\"")
print("the name of the father of the student is : \""+student_father_name+"\"")
print("the updating value of the computerized national identif card of the student is : \""+student_cnic+"\"")
print("the updating value of the student age of the student is = \""+str(student_age)+" years\"")
print("the updaitng value of the contac number of the student is : \""+student_contact_number+"\"")