# write a python program to create a file , and then get the user name , user address , user gender , user university , user faculty , user age , and at the end user birth date by using function methods =>
createFile = open("informationOfUser.txt" , "w+")
fristName = input("please enter the frist name of the user is : ")
secondName = input("please enter the second name of the user is : ")
lastName = input("please enter the last name of the user is : ")
userAddress = input("please enter the address of the user is : ")
userGender = input("please enter the gender of the user is : ")
userUniversity = input("please enter the university of the user is : ")
userFaculty = input("please enter the faculty of the user is : ")
userAge = int(input("please enter the age of the user is : "))
userBirthDate = input("please enter the birthdate of the user is : ")
def createFileOfUserInformation(cFile , friName , secName , lastName , address , gender , university , faculty , age , birthDate) :
    cFile.write("The Frist Name Of The User Is : \""+friName+"\"\n")
    cFile.write("The Second Name Of The User Is : \""+secName+"\"\n")
    cFile.write("The Last Name Of The User Is : \""+lastName+"\"\n")
    cFile.write("The Full Name Of The User Is : \""+friName+" "+secName+" "+lastName+"\"\n")
    cFile.write("The Address Of The User Is : \""+address+"\"\n")
    cFile.write("The Gender Of The User Is : \""+gender+"\"\n")
    cFile.write("The University Of The User Is : \""+university+"\"\n")
    cFile.write("The Faculty Of The User Is : \""+faculty+"\"\n")
    cFile.write("The Age Of The User Is : \""+str(age)+"\"\n")
    cFile.write("The Birth Date Of The User Is : \""+birthDate+"\"\n")
    cFile.close()
createFileOfUserInformation(createFile , fristName , secondName , lastName , userAddress , userGender , userUniversity , userFaculty , userAge , userBirthDate)